### ISSUE TITLE
Memoize Grid Output

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#125]
With Sass 3.3's Data Map feature, we'll be able to [memoize](http://en.wikipedia.org/wiki/Memoization) our grid output, significantly speeding up Singularity for span combinations that are used more than once. I'm thinking of something like the following:

What we have: `$span`, `$location`, `$grid`, `$gutter`, `$style`, `$output`. We can use these to create Map keys and store a map of values that have been pre-calculated. We could have something like the following (yaml, for ease of reading):

``` yaml
span-location-grid-gutter-style:
  - span: grid-span($span, $location, $grid, $gutter, $style)
  - gutter: gutter-span($gutter, $location)
```

etc…

Each different combination would get their own unique key and we'd store the relevant calculated values in there for ease of reference.
