### ISSUE TITLE
Last column padding using grid-span()

### ISSUE THREAD

**Issue by robdecker** [at-import/Singularity#147]
The last column of a grid-span is correctly floated to the right, but also has right padding. Is there a way to have no right padding without manually `padding-right: 0`? 

Here's the sass:

``` scss
// Content widths
$w-tablet-vertical-width: 601px;
$w-tablet-horizontal-width: 769px;
$w-desktop-width-min: 1025px;
$w-desktop-width-max: 1170px;

// Breakpoint media queries
$break-tablet-vertical: $w-tablet-vertical-width;
$break-tablet-horizontal: $w-tablet-horizontal-width;
$break-desktop: $w-desktop-width-min, 'no-query' true;

$grids: 2;
$grids: add-grid(3 at $w-tablet-vertical-width);
$grids: add-grid(12 at $w-desktop-width-min);

$gutters: 20px;
$gutters: add-gutter(30px at $w-desktop-width-min);

body.sidebar-second {
  .main-content {
    @include breakpoint($break-desktop) {
      @include grid-span(9, 1);
    }
  }

  .sidebar--second {
    @include breakpoint($break-desktop) {
      @include grid-span(3, 10);
      // I don't want to do this: padding-right: 0;
    }
  }
}
```

Output css:

``` css
@media (min-width: 1025px) {
  body.sidebar-second .main-content {
    width: 75%;
    float: left;
    margin-right: -100%;
    margin-left: 0%;
    clear: none;
    padding-right: 30px;
  }
}

@media (min-width: 1025px) {
  body.sidebar-second .sidebar--second {
    width: 25%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none;
    padding-right: 30px;
  }
}
```
