### ISSUE TITLE
background-grid mixin not working at all

### ISSUE THREAD

**Issue by iaakash** [at-import/Singularity#153]
Below is my code for a wrapper and background-grid mixin is not ouputting it's value

``` scss
.footerWidgetContainer{
    $grids:3;$gutters:1/20;
    @include background-grid;

    @extend %clearfix;

    .widget{
        @include float-span(1);
            &:nth-last-child(1){
                @include float-span(1,last);
            }
    } 
}
```
