### ISSUE TITLE
"Color stops must be specified in increasing order" error

### ISSUE THREAD

**Issue by OnkelTem** [at-import/Singularity#174]
Version 1.1.2

I have the following scss:

``` scss
// Load external libraries.
@import "compass";
@import "singularitygs";

$desk: 1200px;
$grids: 1 3;
$gutters: 1/3;
$gutter-styles: split;

#header>.inner {
  width: $desk;
  margin: 1em auto;
  @include pie-clearfix;
  @include background-grid;
}
```

and get this error:

```
Color stops must be specified in increasing order. 96.42857142857142 came after 99.99999999999999.
    on line 69 of /home/.../.rvm/gems/ruby-1.9.3-p448/gems/compass-0.12.5/frameworks/compass/stylesheets/compass/css3/_images.scss, in `background-image'
    from line 255 of /home/.../.rvm/gems/ruby-1.9.3-p448/gems/singularitygs-1.1.2/stylesheets/singularitygs/helpers/_background-grid.scss, in `background-gradient-generate'
    from line 214 of /home/.../.rvm/gems/ruby-1.9.3-p448/gems/singularitygs-1.1.2/stylesheets/singularitygs/helpers/_background-grid.scss, in `background-build'
    from line 136 of /home/.../.rvm/gems/ruby-1.9.3-p448/gems/singularitygs-1.1.2/stylesheets/singularitygs/helpers/_background-grid.scss, in `background-grid'
    from line 42 of /var/www/sites/.../sass/grid.scss, in `grid-background'
    from line 50 of /var/www/sites/.../sass/grid.scss";
```

Any ideas?
