### ISSUE TITLE
Fixed Gutters doesn't seems to work

### ISSUE THREAD

**Issue by OnkelTem** [at-import/Singularity#175]
Version 1.1.2

Following the manual:

``` scss
$desk: 1200px;
$grids: 5;
$gutters: 1em;

$debug-grid: true;

@mixin grid-background {
  @if $debug-grid == true {
    @include background-grid;
  }
}

#header>.inner {
  width: $desk;
  margin: 1em auto;
  @include pie-clearfix;
  @include grid-background;
}


#main>.inner {
  width: $desk;
  margin: 1em auto;
  @include pie-clearfix;
  @include grid-background;
}

#logo {
  @include grid-span(1, 1);
}

#slogan {
  @include grid-span(1, 2);
}

#sidebar {
  @include grid-span(1, 1);
}

#content {
  @include grid-span(1, 2);
}
```

What I get is a complete messup: 
![snapshot53](https://cloud.githubusercontent.com/assets/114060/2632652/52b55476-be66-11e3-9703-ebc0b939cf74.png)

as you see:
1) blocks are intersect
2) grid picture is wrong too: gutters are of the same width as colums
