### ISSUE TITLE
Split gutter style not working

### ISSUE THREAD

**Issue by jstoller** [at-import/Singularity#198]
Given the following setup...

``` scss
$front-grids: sgs-get('front grids'); // Returns valid grid map.
$front-gutters: sgs-get('front gutters'); // Returns valid gutter map.
$front-gutter-styles: 'split' 'fixed';

@mixin front-layout {
  @include layout($front-grids, $front-gutters, $gutter-style: $front-gutter-styles) {
    // All the things!
    @content;
  }
}
@mixin front-grid-span($span, $location) {
  @include front-layout {
    @include grid-span($span, $location);
  }
}

.front-headline--list-item {
    &:nth-child(4n-3) {
      @include front-grid-span(1, 1);
      clear: both;
    }
    &:nth-child(4n-2) {
      @include front-grid-span(1, 2);
    }
    &:nth-child(4n-1) {
      @include front-grid-span(1, 3);
    }
    &:nth-child(4n-0) {
      @include front-grid-span(1, 4);
    }
}
```

...my `.front-headline--list-item` elements are rendered with the default 'opposite' gutter style, instead of 'split'. I've tried numerous variations of this. I've defined the `$front-gutter-styles` variable both as a map and as a string (shown here). I've also tried different methods of passing the gutter style to that `grid-span()` function, but nothing seems to work. I can never get split gutters. At this point I'm assuming its a bug.
