### ISSUE TITLE
Gridsets

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#22]
A bit far off, but the ability to have different grids at different breakpoints would be awesome. We're going to need to think long and hard about the DX for this though.

**Comment by scottkellum** [comment]
Not sure how this isn’t already implemented. The layout can be adjusted or re-written in full anywhere in the cascade.

**Comment by Snugug** [comment]
Really? Guess I just haven't played around with it to see how it works quite yet.

**Comment by scottkellum** [comment]
Yup, no info is stored and the grid is calculated with each mixin/funciton. Each new var will override previous vars.

**Comment by Snugug** [comment]
Hmm, that could get messy to keep everything together. If I had three different layouts, I would my variables for each MQ whenever I write, so I would need to do something like this:

``` scss
$columns: 4;
$bkpt: 500px

#foo {
  @include grid-span(3, 1);
  @include breakpoint($bkpt) {
    $columns: ratio(4/3, 5);
    @include grid-span(2, 1);
  }
  $columns: 4;
}

#bar {
  @include grid-span(1, 3);
  @include breakpoint($bkpt) {
    $columns: ratio(4/3, 5);
    @include grid-span(3, 2);
  }
  $columns: 4;
}
```

If so, that gets unweildy super duper quick and may actually do weird things to the column counting.

**Comment by scottkellum** [comment]
``` scss
$columns: 4;
$bkpt: 500px

#foo {
  @include grid-span(3, 1);
  @include breakpoint($bkpt) {
    @include grid-span(2, 1, ratio(4/3, 5));
  }
}

#bar {
  @include grid-span(1, 3);
  @include breakpoint($bkpt) {
    @include grid-span(3, 2, ratio(4/3, 5));
  }
}
```

better?

**Comment by Snugug** [comment]
Still not very dry. I think I've got an idea how we can make this more user friendly using the Breakpoint Context stuff I just wrote. We'll talk Tuesday if you're not too exhausted.

**Comment by scottkellum** [comment]
Curious as to how this can get DRY-er. Having a dependency on breakpoint bothers me for syntax reasons. But if it enhances instead of changing current behavior it should be fine.

**Comment by Snugug** [comment]
What syntax reasons? And I think it'll enhance the usability of Singularity greatly.

**Comment by scottkellum** [comment]
I want Singularity to be accessible for people who want to use the native `@media (min-width: $whatever)` syntax.

**Comment by Snugug** [comment]
You can 100% do that with or without Breakpoint

**Comment by Snugug** [comment]
I'm thinking something like this (yes I'm about to write Sass pseudocode):

``` sass
$gridsets: 1 623px, compound(3, 4) 800px, ratio(1.618, 4)

=grid-span($span, $position)
  $min-width: breakpoint-get-context('min-width')
  @if $min-width < nth(nth($gridsets, 1), 2)
    width: grid-span($span, $position, nth(nth($gridsets, 1), 1)
  @else if $min-width < nth(nth($gridsets, 2), 2)
    width: grid-span($span, $position, nth(nth($gridsets, 2), 1)
  @else
    width: grid-span($span, $position, nth($gridsets, 3)

  float: left
  margin-right: $gutter
```

Something rough like that. I also think, now that I'm writing out something that uses both, that calling the mixin and function the same thing may get confusing.

**Comment by scottkellum** [comment]
I _really_ like the idea of grid sets. lets do it.

I want to see this logic abstracted into another mixnin/function to sort out what gridset should be included. That way it can be easily plugged into the object generator mixins as easily as the grid span mixin and maintained independently.

**Comment by codingdesigner** [comment]
Ooh. I really like them grid sets too.

**Comment by Snugug** [comment]
Awesomesauce, and now that Breakpoint 1.1 is out, we can do this! _This_ was my usecase for Breakpoint Context.

Okay, so how do we want to see this happen? This is the syntax I'm thinking of, but I don't really like it, so suggestions welcome:

``` scss
// Gridsets are defined as follows:
// default grid, grid1 (min or max width), grid2 (min or max width), etc…
// We will decide if they are min/max width based on whether the sizes are increasing or decreasing.
// We will set $breakpoint-default-feature accordingly

// The following would set up 4 grid breakpoints, a one column grid, a three column grid, a compound 3/4 grid, and a 1.618 5 step grid. The first example sets up the gridsets mobile first, and keeps $breakpoint-default-feature: 'min-width'. The second example would set up the gridsets desktop first, and change to $breakpoint-default-feature: 'max-width'.

$gridsets: 1, 3 445px, compound(3, 4) 792px, ratio(1.618, 5) 900px;
// -or -
$gridsets: ratio(1.618, 5),  compound(3, 4) 900px, 3 792px, 1 445px;

// To call a gridset span, something like the following, but I'm not a huge fan

@include gridset-span($span-list);

// A span list would look something like this

$foo-gridsets: 1 1, 2 1, 2 1, 3 2;

#foo {
  @include breakpoint(760px) {
    @include gridset-span($foo-gridsets);
  }
}

// This would be equal to writing

#foo {
  @include breakpoint(760px) {
    @include grid-span(2, 1);
  }
}
```

Thoughts?
