### ISSUE TITLE
Better compound grid calculations above 2 grids

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#7]
Compound grid math above 2 grids isn’t very accurate yet. Needs work.

**Comment by scottkellum** [comment]
Moved to a feature request. Scope scaled back to only compounding two grids for now.

**Comment by Snugug** [comment]
I'll take a look at this and see if I can figure out X compound grids.

**Comment by Snugug** [comment]
So here's my new proposed syntax:

``` scss
$columns: 4, 6, 8, 'compound';

// 1 column span, 2nd position, 1st grid (4);
#foo {
  @include grid-span(1, 2, $compound-grid: 1);
}

// 2 column span, 3nd position, 2nd grid (6);
#bar {
  @include grid-span(2, 3, $compound-grid: 2);
}

// 2 column span, 2nd position, 3rd grid (8);
#baz {
  @include grid-span(2, 2, $compound-grid: 3);
}
```

I like this for a few reasons: First, instead of creating a new grid, it allows for literal overlaying of grids together (which, as far as I can tell, is the point of compound grids). Second, it can be used with gridsets and isn't such a departure from the way we do `grid-span` already. Third, assuming I've dotted all of my Is and crossed all of my Ts, non compound grids should remain the same. Fourth, it produces bitchin background grids (Seriously! Check out the background grids it makes!) Fifth, and finally, it in theory allows us to compound any grids together we so choose, including symmetric and asymmetric grids (although the float clearing is a bit wonky on first test, but if we like this I'll figure out what's up there).

Disadvantages to this method as opposed creating a new grid (which we previously did): Gutters don't necessarily line up between grids which is potentially especially bad for even/odd compounding, it's potentially confusing and certainly more complicated than creating a new grid, because physical grids can change, it requires a location  (in fact, the more I'm playing with this, especially with anything beyond simply walking across a row, the more I think we should require location in `grid-span`). 

What are your thoughts? [Here's the branch](https://github.com/scottkellum/Singularity/tree/Issue-7-Better-Compound-Grids)
