### ISSUE TITLE
Background grid shows 12 columns regardless set grids

### ISSUE THREAD

**Issue by since1976** [at-import/Singularity#71]
The background grid seems to only show a 12 column grid regardless of what  breakpoint I'm at or what grid is specified. Is this correct behaviour?

``` SCSS
$base-font-size: 1em;
// Set up grids for different breakpoints
$grids: 3, 6 500px, 7 900px;
$grids-mobile-first: true;
$gutters: .25, .3, .4;
$paddings: 0, .5em;

// Set widths for the container
$container: 90%;
$breakpoint-to-ems: true;
$container-to-ems: true;

@include base-font-sizing;
#contain {
  @include background-grid;
  @include container;
  margin: 0 auto;
}


.content-primary {
  @include grid-span(3, 1);

  @include breakpoint(500px) {
    @include grid-span(4, 1);
  }

  @include breakpoint(900px) {
    @include grid-span(4, 1);
  }
}
.content-secondary {
  @include grid-span(3, 1);

  @include breakpoint(500px) {
    @include grid-span(2, 5);
  }

  @include breakpoint(900px) {
    @include grid-span(3, 5);
  }
}
```

I'm getting no errors in the terminal. Any help would be appreciated.
