### ISSUE TITLE
Paddings: not adding padding to grid container

### ISSUE THREAD

**Issue by since1976** [at-import/Singularity#72]
Hey there I can't seem to get `$paddings:` working on the --pre release branch, any ideas why that might be?

Version: singularitygs (1.0.alpha.0, 0.0.17)

``` SCSS
$base-font-size: 1em;
// Set up grids for different breakpoints
$grids: 2, 3 480px, 4 768px, 5 960px, 7 1200px;
$grids-mobile-first: true;
$gutters: .25;
$paddings: 1em;

// Set widths for the container
$container: 94%;
$breakpoint-to-ems: true;
$container-to-ems: true;
```

This is the grid that isn't getting the padding put on:

``` SCSS
.content-primary {
    background: lighten($gray, 30%);
    min-height: 26em;
    @include grid-span(2, 1);

    @include breakpoint(480px) {
        @include grid-span(3, 1);
    }
}
```
