### ISSUE TITLE
Containers for page margins.

### ISSUE THREAD

**Issue by bangpound** [at-import/Singularity#91]
In #21 and #26, there were discussions and commits made for implementing a container mixin which would make it possible to add some space between the edge of the page and the edge of the browser window.

The outcome of #21 appeared to be a container mixin that was later removed from the project.

I can add padding to the grid container, but then my grid background is misaligned.

Since there are many ways to accomplish this, can we get an example which shows how to do this? The project's current examples focus on the strengths of the framework's grid mixins to create previously difficult responsive asymmetrical grids.

Can we get an example that shows something more "traditional" like a centered page with margins that are the same width as the gutters and also including a header, some sidebars and a footer?

**Comment by scottkellum** [comment]
Yeah, removed because there are so many ways to build a container. Here are a few:

``` scss
.container {
  margin: 0 5%;
}
```

``` scss
.container {
  width: 960px;
  margin: 0 auto;
}
```

``` scss
body {
  padding: 0 5%;
  .container {
    // nothing needed here
  }
}
```

``` scss
.container {
  position: absolute;
  left: 20px;
  right: 20px;
}
```

So many really easy and different ways to write a container. I never really liked having a mixin for them. Hope this helps.

**Comment by Snugug** [comment]
So the focus of Singularity has changed from a Grid System a la Susy to a Grid Framework, and as such things that aren't absolutely necessary to what makes a grid a grid in CSS were removed. This includes a container mixin, as the CSS for making a container is very basic (CSS width plus `margin: 0 auto;`). Singularity's focus is the grid, not the context of the grid.

As for examples that can be applied directly to a traditional website structure, take a look at the [Asymmetric Grid](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#asymmetric-grids) page which shows how to create a grid that would be similar to a traditional triptych, or "holy grail" layout. There are also [demos that you can install](https://github.com/Team-Sass/Singularity/wiki/Installation#singularity-demos) to see Singularity in action, which can show you how to use all of the pieces together and how they all work together. 

As for the grid background being misaligned, it's important to remember that the Grid Visualization [is just an approximation](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#visualizing-your-grids) and shouldn't be used to actually align items. If you'd like to see a mixin that includes allowances for padding, please write a feature request for [Singularity Extras](https://github.com/Team-Sass/Singularity-extras/issues).

If you would like a container mixin, please write a feature request for [Singularity Extras](https://github.com/Team-Sass/Singularity-extras/issues) as that is currently the place for miscellaneous items related to Singularity but do not belong in the Core system. Please make the request as specific as possible, as opposed to simply "I'd like a container mixin" as that is much too broad.

Finally, here's a little snippet for turning the triptych into a "traditional" website with a "traditional" 960px max width. I'm going to utilize Asymmetric Grids and the [Isolation Output Span](https://github.com/Team-Sass/Singularity/wiki/Spanning-The-Grid#isolation-span).

``` scss
@import 'singularitygs';

$grids: 2 8 2;
$gutters: 1/3;

// Apply Border Box to all elements. Don't worry, totally safe.
* {
  @include box-sizing('border-box');
}

.container {
  // Sets a max width. Site will be fluid until it reaches 960px, then stick there.
  max-width: 960px;
  // Centers the container.
  margin: 0 auto;
  // Sets padding equal to a gutter.
  padding-left: gutter-span();
  padding-right: gutter-span();
  // Might as well clearfix it as well.
  @include clearfix;
}

#header {
  // You can either span all three columns…
  @include isolation-span(3, 1, 'both');
  // Or you can just clear everything…
  clear: both;
}

#main {
  // We want it to be the middle item. If we used Isolation Span above…
  @include isolation-span(1, 2, 'right');
  // If we simply used clear: both;
  @include isolation-span(1, 2);
}

#sidebar-first {
  @include isolation-span(1, 1);
}

#sidebar-second {
  @include isolation-span(1, 3);
}

#footer {
  // Again, you can either span all three columns…
  @include isolation-span(3, 1, 'both');
  // Or you can just clear everything…
  clear: both;
}
```
